version: 2.1

orbs:
  node: circleci/node@5.1.0

jobs:
  build-and-test:
    docker:
      - image: cimg/node:20.12.0
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Linter (TypeScript Verification)
          command: npm run lint
      - run:
          name: Build React App and Bundle Express Server
          command: npm run build

workflows:
  build-pipeline:
    jobs:
      - build-and-test
