version: 2.1
orbs:
  flutter: circleci/flutter@2.0.0

jobs:
  build_apk:
    docker:
      - image: cimg/android:2024.12
    steps:
      - checkout
      - flutter/install_sdk:
          version: stable
      - run:
          name: Clean Project
          command: flutter clean
      - run:
          name: Get Dependencies
          command: flutter pub get
      - run:
          name: Build Release APK
          command: flutter build apk --release --no-shrink
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
          destination: app-release.apk

workflows:
  build_and_deploy:
    jobs:
      - build_apk
