name: Android EAS Build (APK)

on:
  push:
    branches:
      - main 

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: 🏗 Check out repository
        uses: actions/checkout@v4

      - name: 📦 Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 8 # أو الإصدار الذي تفضله

      - name: ⚙️ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm' # قمنا بتغيير الكاش إلى pnpm

      - name: ⚙️ Setup Expo EAS
        uses: expo/expo-github-action@v8
        with:
          expo-version: latest
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: pnpm install # قمنا بتغيير الأمر إلى pnpm

      - name: 🚀 Build APK on EAS
        run: eas build --platform android --profile preview --non-interactive
