name: CI with pnpm

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 🛑 Checkout Repository
        uses: actions/checkout@v4

      - name: 🤌 Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10 # يمكنك تحديد رقم الإصدار المطلوب

      - name: ⎔ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # حدد إصدار Node.js المناسب لمشروعك
          cache: 'pnpm'

      - name: 📥 Install Dependencies
        run: pnpm install --frozen-lockfile
        
      - name: 🏗️ Build Android APK via EAS
        run: pnpm exec eas build --platform android --profile preview --local --non-interactive
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
